import type { ContentEntry, Locale } from "./types";

export const defaultSettings = {
  phone: "+31851091145",
  phoneDisplay: "085 109 11 45",
  whatsapp: "+31617480856",
  email: "info@formicabouw.com",
  kvk: "92293255",
  instagram: "https://www.instagram.com/formicabouw/",
  serviceAreaNl: "Door heel Nederland",
  serviceAreaEn: "Across the Netherlands",
};

const page = (
  id: string,
  slug: string,
  titleNl: string,
  titleEn: string,
  summaryNl: string,
  summaryEn: string,
  bodyNl = "",
  bodyEn = "",
  sortOrder = 0,
): ContentEntry => ({
  id,
  contentType: "page",
  slug,
  status: "published",
  titleNl,
  titleEn,
  summaryNl,
  summaryEn,
  bodyNl,
  bodyEn,
  metadata: {},
  sortOrder,
});

export const seedContent: ContentEntry[] = [
  {
    id: "settings-global",
    contentType: "settings",
    slug: "global",
    status: "published",
    titleNl: "Formica Bouw",
    titleEn: "Formica Bouw",
    summaryNl: "Esthetisch bouwen en renoveren",
    summaryEn: "Considered construction and renovation",
    bodyNl: "",
    bodyEn: "",
    metadata: defaultSettings,
    sortOrder: 0,
  },
  page(
    "page-home",
    "home",
    "Uw nieuwe badkamer, tot in detail gerealiseerd.",
    "Your new bathroom, delivered down to the last detail.",
    "Van sloop en leidingwerk tot tegelwerk en afwerking: één betrokken specialist voor uw complete badkamerrenovatie.",
    "From demolition and plumbing to tiling and finishes: one committed specialist for your complete bathroom renovation.",
    "Formica Bouw realiseert complete badkamers met één helder plan, één aanspreekpunt en aandacht voor iedere aansluiting, voeg en afwerking.",
    "Formica Bouw delivers complete bathrooms with one clear plan, one point of contact and attention to every fitting, joint and finish.",
  ),
  page(
    "page-services",
    "services",
    "Badkamers als specialisme. De rest vakkundig geregeld.",
    "Bathrooms are our speciality. Everything else expertly handled.",
    "Complete badkamerrenovaties, aangevuld met specialistisch werk voor een woning die technisch en esthetisch klopt.",
    "Complete bathroom renovations, supported by specialist work for a home that performs and looks right.",
  ),
  page(
    "page-projects",
    "projects",
    "Werk dat voor zichzelf spreekt",
    "Work that speaks for itself",
    "Een selectie van renovaties, maatwerk en afwerking uit ons portfolio.",
    "A selection of renovations, bespoke work and finishes from our portfolio.",
  ),
  page(
    "page-about",
    "about",
    "Gebouwd op aandacht",
    "Built on attention",
    "Formica Bouw is een betrokken bouwpartner voor particuliere renovaties en woningverbetering door heel Nederland.",
    "Formica Bouw is a committed construction partner for residential renovations and home improvement across the Netherlands.",
    "We benaderen iedere opdracht met zorg voor de woning, de planning en de mensen die er wonen. Van eerste idee tot oplevering houden we de lijnen kort en de afspraken helder.",
    "We approach every commission with care for the home, the schedule and the people living there. From the first idea to handover, communication stays direct and expectations clear.",
  ),
  page(
    "page-contact",
    "contact",
    "Uw nieuwe badkamer begint met één bericht",
    "Your new bathroom starts with one message",
    "Stuur uw wensen of een paar foto’s. We denken persoonlijk met u mee over indeling, uitvoering en de volgende stap.",
    "Send us your ideas or a few photos. We will personally think along about the layout, delivery and the next step.",
  ),
  page(
    "page-quote",
    "quote",
    "Vertel ons over uw nieuwe badkamer",
    "Tell us about your new bathroom",
    "Deel uw wensen en eventueel enkele foto’s. Wij bekijken de ruimte en nemen persoonlijk contact met u op.",
    "Share your wishes and, if useful, a few photos. We will review the space and contact you personally.",
  ),
  page(
    "page-privacy",
    "privacy",
    "Privacybeleid",
    "Privacy policy",
    "Concept — controle door de onderneming of juridisch adviseur vereist vóór publicatie.",
    "Draft — review by the business or legal counsel is required before publication.",
    "Formica Bouw verwerkt de gegevens die u via het offerteformulier verstrekt om uw aanvraag te beoordelen en contact met u op te nemen. Aanvragen worden in beginsel niet langer bewaard dan noodzakelijk; afgesloten aanvragen ouder dan twaalf maanden worden gemarkeerd voor verwijdering. Het beheergedeelte is beschermd met een privé superadmin-account en een ondertekende sessiecookie. Formuliermeldingen worden via Resend naar info@formicabouw.com verzonden. Projectfoto’s worden alleen gebruikt om uw aanvraag te beoordelen. U kunt verzoeken om inzage, correctie of verwijdering via info@formicabouw.com. Deze tekst is een werkconcept en geen juridisch advies.",
    "Formica Bouw processes the details you provide through the quote form to assess your request and contact you. Requests are not kept longer than necessary; closed requests older than twelve months are flagged for deletion. The administration area is protected by a private superadmin account and a signed session cookie. Form notifications are sent to info@formicabouw.com through Resend. Project photos are used only to assess your request. You can request access, correction or deletion via info@formicabouw.com. This text is a working draft and does not constitute legal advice.",
  ),
  page(
    "page-cookies",
    "cookies",
    "Cookiebeleid",
    "Cookie policy",
    "Concept — de publieke site gebruikt geen analytische of marketingcookies.",
    "Draft — the public site uses no analytics or marketing cookies.",
    "De publieke website plaatst geen analytische, marketing- of taalkeuzecookies. Voor het beveiligde beheergedeelte plaatst de website na een geldige superadmin-login één strikt noodzakelijke, ondertekende HttpOnly-sessiecookie. Deze cookie verloopt na acht uur, wordt niet gebruikt voor advertentiedoeleinden en bevat geen wachtwoord. Deze tekst is een werkconcept en moet vóór publicatie worden gecontroleerd.",
    "The public website does not place analytics, marketing or language-preference cookies. After a valid superadmin login, the secured administration area sets one strictly necessary, signed HttpOnly session cookie. This cookie expires after eight hours, is not used for advertising and does not contain the password. This text is a working draft and must be reviewed before publication.",
  ),
  {
    id: "service-renovations",
    contentType: "service",
    slug: "renovations",
    status: "published",
    titleNl: "Complete badkamerrenovatie",
    titleEn: "Complete bathroom renovation",
    summaryNl: "Eén specialist voor sloop, leidingwerk, elektra, tegelwerk, sanitair en de perfecte afwerking.",
    summaryEn: "One specialist for demolition, plumbing, electrical work, tiling, sanitaryware and the perfect finish.",
    bodyNl: "We begeleiden uw badkamer van eerste opname tot de laatste kitnaad. We bespreken indeling, materiaal en comfort, verzorgen het voorbereidende werk en stemmen leidingwerk, elektra, tegelwerk en montage zorgvuldig op elkaar af. U heeft één aanspreekpunt en ontvangt een helder voorstel, zodat u precies weet waar u aan toe bent.",
    bodyEn: "We guide your bathroom from the first survey to the final seal. We discuss layout, materials and comfort, handle all preparation and carefully coordinate plumbing, electrical work, tiling and installation. You have one point of contact and receive a clear proposal, so you always know what to expect.",
    metadata: { image: "/media/details/renovation-modern-bath.jpg", category: "renovation" },
    sortOrder: 1,
  },
  {
    id: "service-insulation",
    contentType: "service",
    slug: "insulation",
    status: "published",
    titleNl: "Isolatie & verduurzaming",
    titleEn: "Insulation & sustainability",
    summaryNl: "Praktische verbeteringen voor meer comfort, een lager energiegebruik en een toekomstbestendige woning.",
    summaryEn: "Practical improvements for greater comfort, lower energy use and a more future-ready home.",
    bodyNl: "Een comfortabele woning begint bij een goede analyse. We bekijken waar warmte verloren gaat en welke ingrepen logisch aansluiten op uw woning en plannen. Denk aan isolatie, kierdichting en technische verbeteringen. U ontvangt een overzichtelijk advies, een duidelijke offerte en begeleiding tijdens de uitvoering.",
    bodyEn: "A comfortable home starts with a sound assessment. We look at where heat is lost and which improvements make sense for your home and plans, from insulation and draught proofing to technical upgrades. You receive a clear recommendation, transparent proposal and guidance throughout delivery.",
    metadata: { image: "/media/services/insulation.jpeg", category: "insulation" },
    sortOrder: 2,
  },
  {
    id: "service-custom",
    contentType: "service",
    slug: "custom-kitchens-cabinets",
    status: "published",
    titleNl: "Keukens & kasten op maat",
    titleEn: "Bespoke kitchens & cabinetry",
    summaryNl: "Maatwerk dat ruimte optimaal benut en als vanzelf onderdeel wordt van het interieur.",
    summaryEn: "Bespoke work that makes full use of the space and feels integral to the interior.",
    bodyNl: "We vertalen uw opbergbehoefte, smaak en beschikbare ruimte naar een functioneel ontwerp. Materiaal, indeling en afwerking worden zorgvuldig gekozen. Van inbouwkast tot complete keuken: ieder onderdeel wordt op maat uitgewerkt en met aandacht gemonteerd.",
    bodyEn: "We translate your storage needs, taste and available space into a functional design. Materials, layout and finishes are carefully selected. From fitted wardrobes to a complete kitchen, every element is developed to measure and installed with care.",
    metadata: { image: "/media/services/kitchen.jpg", category: "custom" },
    sortOrder: 3,
  },
  {
    id: "service-finishing",
    contentType: "service",
    slug: "plastering-painting",
    status: "published",
    titleNl: "Stuc- & schilderwerk",
    titleEn: "Plastering & painting",
    summaryNl: "Strakke ondergronden en duurzame afwerkingen voor een rustig, verzorgd eindbeeld.",
    summaryEn: "Precise surfaces and durable finishes for a calm, considered result.",
    bodyNl: "Een hoogwaardige afwerking begint met een goede voorbereiding. Onze werkzaamheden omvatten herstel, egaliseren, stucwerk, primer en binnen- of buitenschilderwerk. We stemmen kleur, glansgraad en materiaal af op het gebruik van de ruimte en het gewenste resultaat.",
    bodyEn: "A high-quality finish begins with careful preparation. Our work includes repairs, levelling, plastering, priming and interior or exterior painting. Colour, sheen and material are selected to suit the space and the intended result.",
    metadata: { image: "/media/services/plaster.jpg", category: "finishing" },
    sortOrder: 4,
  },
  {
    id: "service-electrical",
    contentType: "service",
    slug: "ev-charging-electrical",
    status: "published",
    titleNl: "Laadpalen & elektra",
    titleEn: "EV charging & electrical",
    summaryNl: "Veilige elektrische installaties, uitbreidingen en laadoplossingen voor woning en oprit.",
    summaryEn: "Safe electrical installations, upgrades and charging solutions for your home and driveway.",
    bodyNl: "We verzorgen elektrische werkzaamheden binnen renovaties en als zelfstandige opdracht. Dat omvat verlichting, aansluitpunten, groepenkasten, bekabeling en laadoplossingen. Vooraf bespreken we capaciteit, plaatsing en gebruik, zodat de installatie veilig en logisch wordt uitgevoerd.",
    bodyEn: "We deliver electrical work as part of renovations and as standalone projects. This includes lighting, sockets, consumer units, cabling and EV charging solutions. Capacity, positioning and use are discussed in advance so the installation is safe and considered.",
    metadata: { image: "/media/services/charging.jpg", category: "electrical" },
    sortOrder: 5,
  },
  ...[
    ["project-01", "Lichte leefruimte", "Bright living space", "renovation", "/media/projects/project-01.jpg"],
    ["project-02", "Maatwerk in detail", "Bespoke detail", "custom", "/media/projects/project-02.png"],
    ["project-03", "Rustige afwerking", "Considered finishes", "finishing", "/media/projects/project-03.jpg"],
    ["project-04", "Interieur op maat", "Interior made to measure", "custom", "/media/projects/project-04.png"],
    ["project-05", "Woning in balans", "A balanced home", "renovation", "/media/projects/project-05.jpg"],
    ["project-06", "Ruimte en karakter", "Space and character", "renovation", "/media/projects/project-06.jpg"],
    ["project-07", "Nauwkeurige uitvoering", "Precise delivery", "finishing", "/media/projects/project-07.jpg"],
    ["project-08", "Van plan naar plek", "From plan to place", "renovation", "/media/projects/project-08.jpg"],
  ].map(([id, titleNl, titleEn, category, image], index): ContentEntry => ({
    id,
    contentType: "project",
    slug: id,
    status: "published",
    titleNl,
    titleEn,
    summaryNl: "Selectie uit het bestaande Formica Bouw portfolio.",
    summaryEn: "Selected work from the existing Formica Bouw portfolio.",
    bodyNl: "",
    bodyEn: "",
    metadata: { category, image, featured: index < 4 },
    sortOrder: index + 1,
  })),
  ...[
    ["partner-winkel2", "Winkel2", "/media/partners/winkel2.jpg"],
    ["partner-sani4all", "Sani4All", "/media/partners/sani4all.png"],
    ["partner-03", "Partner", "/media/partners/partner-03.png"],
    ["partner-04", "Partner", "/media/partners/partner-04.png"],
  ].map(([id, name, image], index): ContentEntry => ({
    id,
    contentType: "partner",
    slug: id,
    status: "published",
    titleNl: name,
    titleEn: name,
    summaryNl: "",
    summaryEn: "",
    bodyNl: "",
    bodyEn: "",
    metadata: { image },
    sortOrder: index + 1,
  })),
  {
    id: "claim-financing",
    contentType: "claim",
    slug: "financing-energy-label",
    status: "draft",
    titleNl: "Financiering en energielabel",
    titleEn: "Financing and energy label",
    summaryNl: "Bestaande claims over bankrente, extra hypotheek en energielabel. Alleen publiceren na verificatie.",
    summaryEn: "Existing claims about interest rates, additional mortgages and energy labels. Publish only after verification.",
    bodyNl: "",
    bodyEn: "",
    metadata: {},
    sortOrder: 1,
  },
];

export const nlPaths: Record<string, string> = {
  home: "/",
  services: "/diensten",
  renovations: "/renovaties",
  insulation: "/isolatie",
  "custom-kitchens-cabinets": "/keukens-kasten-op-maat",
  "plastering-painting": "/stucen-en-schilderen",
  "ev-charging-electrical": "/laadpalen-en-elektra",
  projects: "/projecten",
  about: "/over-ons",
  contact: "/contact",
  quote: "/offerte",
  privacy: "/privacybeleid",
  cookies: "/cookiebeleid",
};

export const enPaths: Record<string, string> = {
  home: "/en",
  services: "/en/services",
  renovations: "/en/renovations",
  insulation: "/en/insulation-sustainability",
  "custom-kitchens-cabinets": "/en/custom-kitchens-cabinets",
  "plastering-painting": "/en/plastering-painting",
  "ev-charging-electrical": "/en/ev-charging-electrical",
  projects: "/en/projects",
  about: "/en/about",
  contact: "/en/contact",
  quote: "/en/quote",
  privacy: "/en/privacy",
  cookies: "/en/cookies",
};

export const pathFor = (key: string, locale: Locale) =>
  (locale === "nl" ? nlPaths : enPaths)[key] ?? (locale === "nl" ? "/" : "/en");

const reverse = (paths: Record<string, string>) =>
  Object.fromEntries(Object.entries(paths).map(([key, value]) => [value.replace(/^\/(en\/)?/, ""), key]));

export const nlRouteKeys = reverse(nlPaths);
export const enRouteKeys = reverse(enPaths);

export const getLocalized = (entry: ContentEntry, locale: Locale) => ({
  title: locale === "nl" ? entry.titleNl : entry.titleEn,
  summary: locale === "nl" ? entry.summaryNl : entry.summaryEn,
  body: locale === "nl" ? entry.bodyNl : entry.bodyEn,
});
